// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvCDYCLSnbP8qNc9cVYKgg62op3hACyok',
    appId: '1:219834687240:web:2a40647e4801d48d4dd6bd',
    messagingSenderId: '219834687240',
    projectId: 'chatting-application-1bf76',
    authDomain: 'chatting-application-1bf76.firebaseapp.com',
    storageBucket: 'chatting-application-1bf76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCs6XmhYNSTNVQkcxG0upp8fv4cQ0vCLI',
    appId: '1:219834687240:android:9f8cf12551a05c4e4dd6bd',
    messagingSenderId: '219834687240',
    projectId: 'chatting-application-1bf76',
    storageBucket: 'chatting-application-1bf76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs0YtV_g9WaQ3-I80iaOUpfEh2xM8aP00',
    appId: '1:219834687240:ios:174eff96f3b075104dd6bd',
    messagingSenderId: '219834687240',
    projectId: 'chatting-application-1bf76',
    storageBucket: 'chatting-application-1bf76.appspot.com',
    iosBundleId: 'com.example.chattingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs0YtV_g9WaQ3-I80iaOUpfEh2xM8aP00',
    appId: '1:219834687240:ios:174eff96f3b075104dd6bd',
    messagingSenderId: '219834687240',
    projectId: 'chatting-application-1bf76',
    storageBucket: 'chatting-application-1bf76.appspot.com',
    iosBundleId: 'com.example.chattingApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvCDYCLSnbP8qNc9cVYKgg62op3hACyok',
    appId: '1:219834687240:web:5211842f0da858e34dd6bd',
    messagingSenderId: '219834687240',
    projectId: 'chatting-application-1bf76',
    authDomain: 'chatting-application-1bf76.firebaseapp.com',
    storageBucket: 'chatting-application-1bf76.appspot.com',
  );
}
